const seed=[
{id:'demo1',day:'Sun Aug 30',start:'18:00',end:'20:00',name:'Welcome Playa Dinner',cat:'Food',camp:'Demo Camp',priority:'⭐'},
{id:'demo2',day:'Sun Aug 30',start:'19:00',end:'21:00',name:'Sunset Art Ride',cat:'Art',camp:'Open Playa',priority:'🔥'},
{id:'demo3',day:'Sun Aug 30',start:'20:30',end:'23:00',name:'House & Disco',cat:'Music',camp:'Demo Sound Camp',priority:'🔥'},
{id:'demo4',day:'Mon Aug 31',start:'09:00',end:'10:00',name:'Playa Yoga',cat:'Wellness',camp:'Demo Camp',priority:'⭐'},
{id:'demo5',day:'Mon Aug 31',start:'21:00',end:'23:30',name:'Fire Performance',cat:'Performance',camp:'Open Playa',priority:'🔥'},
{id:'demo6',day:'Tue Sep 1',start:'22:00',end:'01:00',name:'Mutant Vehicle DJ Ride',cat:'Mutant Vehicle',camp:'Roaming',priority:'🔥'}];
let events=JSON.parse(localStorage.getItem('playa-events')||'null')||seed;let selected=JSON.parse(localStorage.getItem('playa-selected')||'[]');let reports=JSON.parse(localStorage.getItem('playa-reports')||'[]');let day='All',cat='All',q='';
const cats=['All','Food','Wellness','Workshop','Art','Performance','Music','Mutant Vehicle','Fire','Couples','Game'];
function mins(t){let [h,m]=t.split(':').map(Number);return h*60+m}function overlaps(a,b){return a.day===b.day&&mins(a.start)<mins(b.end)&&mins(b.start)<mins(a.end)}
function save(){localStorage.setItem('playa-selected',JSON.stringify(selected));localStorage.setItem('playa-reports',JSON.stringify(reports))}
function render(){let days=['All',...new Set(events.map(e=>e.day))];let filtered=events.filter(e=>(day==='All'||e.day===day)&&(cat==='All'||e.cat===cat)&&(!q||JSON.stringify(e).toLowerCase().includes(q.toLowerCase())));document.getElementById('root').innerHTML=`<div class="wrap"><h1>🏜️ PlayaOS</h1><div class="small">Offline-first prototype • local data • ${navigator.onLine?'Online':'Offline'}</div><div class="nav" style="margin:14px 0">${['Explore','My Playa','Monitor'].map(x=>`<button class="${view===x?'on':''}" onclick="view='${x}';render()">${x}</button>`).join('')}</div>${view==='Explore'?explore(filtered,days):view==='My Playa'?itinerary():monitor()}</div>`}
function explore(filtered,days){return `<input placeholder="Search Playa..." value="${q}" oninput="q=this.value;render()"><div class="nav">${days.map(x=>`<button class="${day===x?'on':''}" onclick="day='${x}';render()">${x}</button>`).join('')}</div><div class="nav" style="margin-top:8px">${cats.map(x=>`<button class="${cat===x?'on':''}" onclick="cat='${x}';render()">${x}</button>`).join('')}</div>${filtered.sort((a,b)=>mins(a.start)-mins(b.start)).map(card).join('')||'<p>No activities match.</p>'}`}
function card(e){let on=selected.includes(e.id);return `<div class="card"><div class="row"><div><b>${e.priority} ${e.name}</b><div class="meta">${e.day} • ${e.start}–${e.end}</div></div><button class="${on?'remove':'add'}" onclick="toggle('${e.id}')">${on?'Remove':'＋ Add'}</button></div><span class="tag">${e.cat}</span><span class="tag">${e.camp}</span></div>`}
function itinerary(){let chosen=selected.map(id=>events.find(e=>e.id===id)).filter(Boolean).sort((a,b)=>(a.day+b.start).localeCompare(b.day+a.start));let conflicts=[];chosen.forEach((a,i)=>chosen.slice(i+1).forEach(b=>{if(overlaps(a,b))conflicts.push([a,b])}));return `<h2>❤️ My Playa</h2>${conflicts.length?`<div class="card"><b class="danger">⚠️ ${conflicts.length} conflict${conflicts.length>1?'s':''}</b><p>PlayaOS recommends splitting time or choosing the higher-priority experience.</p>${conflicts.map(([a,b])=>`<div class="card"><b>${a.name}</b> ${a.start}–${a.end}<br><b>vs.</b><br><b>${b.name}</b> ${b.start}–${b.end}<p class="small">Decision: keep both only if travel/partial attendance is realistic.</p></div>`).join('')}</div>`:'<div class="card"><span class="ok">✓ No schedule conflicts.</span></div>'}${chosen.map(card).join('')||'<p>Add activities from Explore.</p>'}`}
function monitor(){return `<h2>📡 Playa Monitor</h2><div class="card"><b>Report a live update</b><input id="rid" placeholder="Event name or ID"><select id="rtype"><option>Correction</option><option>Time changed</option><option>Location changed</option><option>Cancelled</option><option>DJ/artist changed</option><option>Field report</option><option>New event</option></select><textarea id="rtext" placeholder="What did you observe?"></textarea><button class="add" onclick="report()">Submit update</button></div>${reports.length?reports.map(r=>`<div class="card"><b>${r.type}</b> — ${r.target}<div>${r.text}</div><div class="small">${new Date(r.ts).toLocaleString()} • Pending</div></div>`).join(''):'<p>No reports yet. Reports are saved locally while offline.</p>'}`}
function toggle(id){selected=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];save();render()}function report(){let target=document.getElementById('rid').value.trim();let text=document.getElementById('rtext').value.trim();if(!target||!text)return alert('Add an event and report.');reports.unshift({target,type:document.getElementById('rtype').value,text,ts:Date.now()});save();render()}
let view='Explore';render();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');