const state={events:[],selected:new Set(JSON.parse(localStorage.getItem('playa_selected')||'[]')),updates:JSON.parse(localStorage.getItem('playa_updates')||'[]'),activeDay:localStorage.getItem('playa_day')||'all'};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const catLabels={food:'🍳 Food',wellness:'🧖 Wellness',workshop:'🧠 Workshop',art:'🎨 Art',music:'🎧 Music',performance:'🎪 Performance',mutant_vehicle:'🚲 Mutant Vehicle',fire:'🔥 Fire',social:'🍸 Social',games:'🎲 Games',couples:'❤️ Couples',costume:'👗 Costume',photography:'📸 Photo',exploration:'🌀 Exploration',service:'🤝 Service',other:'Other'};
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m}function fmt(t){let [h,m]=t.split(':').map(Number);const ap=h>=12?'PM':'AM';h=h%12||12;return `${h}:${String(m).padStart(2,'0')} ${ap}`}function dayName(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}function shortDay(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',day:'numeric'})}function save(){localStorage.setItem('playa_selected',JSON.stringify([...state.selected]));localStorage.setItem('playa_updates',JSON.stringify(state.updates));localStorage.setItem('playa_day',state.activeDay);updateCounts()}
function upcomingDate(){const days=[...new Set(state.events.map(e=>e.date))].sort();if(!days.length)return'all';const today=new Date();today.setHours(0,0,0,0);const todayStr=today.toISOString().slice(0,10);return days.find(d=>d>=todayStr)||days[0]}
function nextEvents(limit=5){const now=new Date();const today=now.toISOString().slice(0,10);const current=now.getHours()*60+now.getMinutes();return [...state.events].filter(e=>e.status!=='cancelled'&&(e.date>today||(e.date===today&&mins(e.start)>=current))).sort((a,b)=>a.date.localeCompare(b.date)||mins(a.start)-mins(b.start)||mins(a.end)-mins(b.end)||a.title.localeCompare(b.title)).slice(0,limit)}
async function load(){try{const [er,dr]=await Promise.all([fetch('./data/events.json',{cache:'no-store'}),fetch('./data/dj_sets.json',{cache:'no-store'})]);if(!er.ok)throw new Error(`Event data request failed: ${er.status}`);const d=await er.json();const dj=dr.ok?await dr.json():{sets:[]};const djEvents=(dj.sets||[]).map(s=>({id:s.id,date:s.date,start:s.start,end:s.end,title:`🎧 ${s.artist}`,camp:s.camp,category:'music',priority:'must',status:s.status==='confirmed'?'verified':'verified',source_url:s.source_url,artists:[s.artist],genre:s.genre,is_dj_set:true,source_type:'community_confirmed'}));state.events=[...(d.events||[]),...djEvents]}catch(e){console.error('PlayaOS data load failed',e);state.events=[];$('#events').innerHTML='<div class="card">Unable to load Playa event data. Please refresh the app.</div>'}populate();if(state.activeDay==='all'||!state.events.some(e=>e.date===state.activeDay))state.activeDay=upcomingDate();$('#day').value=state.activeDay;renderDateStrip();renderExplore();renderPlan();renderFeed();updateCounts();$('#offline').textContent=navigator.onLine?'Online':'Offline';}
function populate(){const cats=[...new Set(state.events.map(e=>e.category))].sort();$('#category').innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option value="${c}">${catLabels[c]||c}</option>`).join('');$('#reportEvent').innerHTML=state.events.map(e=>`<option value="${e.id}">${esc(e.title)} · ${e.date} ${fmt(e.start)}</option>`).join('');const days=[...new Set(state.events.map(e=>e.date))].sort();$('#day').innerHTML='<option value="all">All days</option>'+days.map(d=>`<option value="${d}">${dayName(d)}</option>`).join('')}
function filtered(){const d=state.activeDay,c=$('#category').value,q=$('#search').value.toLowerCase();return state.events.filter(e=>(d==='all'||e.date===d)&&(c==='all'||e.category===c)&&(!q||`${e.title} ${e.camp} ${e.category} ${(e.artists||[]).join(' ')} ${e.genre||''}`.toLowerCase().includes(q))).sort((a,b)=>a.date.localeCompare(b.date)||mins(a.start)-mins(b.start)||mins(a.end)-mins(b.end)||a.title.localeCompare(b.title))}
function renderDateStrip(){const days=[...new Set(state.events.map(e=>e.date))].sort();$('#dateStrip').innerHTML=days.map(d=>`<button class="dateChip ${state.activeDay===d?'active':''}" data-day="${d}"><strong>${shortDay(d).split(' ')[0]}</strong><span>${shortDay(d).split(' ').slice(1).join(' ')}</span></button>`).join('');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>setDay(b.dataset.day))}
function setDay(day){state.activeDay=day;save();$('#day').value=day;renderDateStrip();renderExplore()}
function renderNextUp(){const next=nextEvents(5);$('#nextUp').innerHTML=next.length?next.map((e,i)=>`<button class="nextCard" data-next="${e.id}"><span class="nextTime">${fmt(e.start)}</span><span class="nextInfo"><strong>${esc(e.title)}</strong><small>${dayName(e.date)} · ${esc(e.camp||'Location TBD')}</small></span><span class="nextArrow">${i===0?'NOW':'→'}</span></button>`).join(''):'<div class="card">No upcoming events found.</div>';document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{const e=state.events.find(x=>x.id===b.dataset.next);if(e)setDay(e.date)})}
function renderEvents(){const ev=filtered();const label=state.activeDay==='all'?'All Playa days':dayName(state.activeDay);$('#dayLabel').textContent=label;$('#events').innerHTML=ev.length?ev.map(e=>`<article class="card event"><div class="time">${fmt(e.start)}<br><span class="meta">${fmt(e.end)}</span></div><div><div class="title">${esc(e.title)}</div><div class="meta">${esc(e.camp||'Location TBD')} · ${dayName(e.date)}</div><span class="tag">${catLabels[e.category]||e.category}</span><span class="tag">${e.status||'verified'}</span>${e.is_dj_set?`<span class="tag">Confirmed DJ</span><span class="tag">${esc(e.genre||'')}</span>`:''}</div><button class="add ${state.selected.has(e.id)?'added':''}" data-add="${e.id}">${state.selected.has(e.id)?'Added':'＋ Add'}</button></article>`).join(''):'<div class="card">No matching activities for this day.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>toggle(b.dataset.add))}
function renderExplore(){renderNextUp();renderEvents();const next=nextEvents(1)[0];$('#jumpNext').textContent=next?'Next event →':'First day →';$('#jumpNext').onclick=()=>next?setDay(next.date):setDay(upcomingDate())}
function toggle(id){state.selected.has(id)?state.selected.delete(id):state.selected.add(id);save();renderEvents();renderPlan()}
function selectedEvents(){return state.events.filter(e=>state.selected.has(e.id)).sort((a,b)=>a.date.localeCompare(b.date)||mins(a.start)-mins(b.start)||mins(a.end)-mins(b.end)||a.title.localeCompare(b.title))}
function conflicts(){const a=selectedEvents(),out=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){if(a[i].date!==a[j].date)continue;const s=Math.max(mins(a[i].start),mins(a[j].start)),en=Math.min(mins(a[i].end),mins(a[j].end));if(en>s)out.push({a:a[i],b:a[j],overlap:en-s})}return out}
function renderPlan(){const c=conflicts();$('#conflicts').innerHTML=c.map(x=>`<div class="conflict"><strong>⚠️ ${x.overlap} min overlap</strong><div>${esc(x.a.title)} · ${fmt(x.a.start)}–${fmt(x.a.end)}</div><div>${esc(x.b.title)} · ${fmt(x.b.start)}–${fmt(x.b.end)}</div><div class="recommend">Recommendation: ${x.overlap<=45?'Split time may work if locations are close.':'Choose one unless one event allows late arrival/early departure.'}</div></div>`).join('');const a=selectedEvents();$('#plan').innerHTML=a.length?a.map(e=>`<article class="card event"><div class="time">${e.date.slice(5)}<br>${fmt(e.start)}</div><div><div class="title">${esc(e.title)}</div><div class="meta">${esc(e.camp||'Location TBD')} · ${fmt(e.end)}</div></div><button class="ghost" data-remove="${e.id}">Remove</button></article>`).join(''):'<div class="card">Nothing selected yet. Add events from Explore.</div>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>toggle(b.dataset.remove))}
function renderFeed(){const feed=[...state.updates].sort((a,b)=>b.created_at.localeCompare(a.created_at));$('#feed').innerHTML=feed.length?feed.map(u=>`<article class="card report"><div><div class="title">${esc(u.event_title)}</div><div class="meta">${esc(u.type)} · ${esc(u.text)}</div><div class="meta">${new Date(u.created_at).toLocaleString()} · <span class="status ${u.status}">${u.status}</span></div></div><span class="tag">${u.confidence}</span></article>`).join(''):'<div class="card">No field reports yet. Be the first to keep the Playa current.</div>'}
function updateCounts(){$('#count').textContent=state.selected.size;$('#updatesCount').textContent=state.updates.length}
function switchView(v){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));['explore','itinerary','monitor'].forEach(x=>$('#'+x+'View').hidden=x!==v)}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#day').addEventListener('change',e=>setDay(e.target.value));['category','search'].forEach(id=>$('#'+id).addEventListener('input',renderEvents));$('#clear').addEventListener('click',()=>{state.selected.clear();save();renderEvents();renderPlan()});$('#report').addEventListener('click',()=>$('#reportDialog').showModal());$('#reportForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#reportEvent').value;const ev=state.events.find(x=>x.id===id);state.updates.push({id:'u-'+Date.now(),event_id:id,event_title:ev?.title||'New event',type:$('#reportType').value,text:$('#reportText').value.trim(),confidence:$('#confidence').value,status:'pending',created_at:new Date().toISOString()});save();renderFeed();$('#reportDialog').close();$('#reportText').value='';switchView('monitor')});window.addEventListener('online',()=>$('#offline').textContent='Online');window.addEventListener('offline',()=>$('#offline').textContent='Offline');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});load();