const $=s=>document.querySelector(s);let pending=[];let memories=JSON.parse(localStorage.getItem('playa_memory_depot')||'[]');
const days=['2026-08-30','2026-08-31','2026-09-01','2026-09-02','2026-09-03','2026-09-04','2026-09-05'];
function fmtDay(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function save(){localStorage.setItem('playa_memory_depot',JSON.stringify(memories))}
function render(){const q=$('#memorySearch').value.toLowerCase(),d=$('#memoryDay').value,k=$('#memoryKind').value;const arr=memories.filter(m=>(d==='all'||m.day===d)&&(k==='all'||m.kind===k)&&(!q||`${m.author} ${m.caption} ${m.location} ${m.event}`.toLowerCase().includes(q)));$('#memoryGrid').innerHTML=arr.length?arr.map(m=>`<article class="memoryCard card"><div class="memoryMedia">${m.kind==='photo'&&m.data?`<img src="${m.data}" alt="${esc(m.caption||'Playa memory')}" loading="lazy">`:m.kind==='video'&&m.data?`<video src="${m.data}" controls preload="metadata"></video>`:`<div class="memoryNote">✦<br><small>PLAYA NOTE</small></div>`}</div><div class="memoryInfo"><strong>${esc(m.caption||'Untitled memory')}</strong><div class="meta">${esc(m.author)}${m.day?' · '+fmtDay(m.day):''}</div>${m.location?`<div class="meta">📍 ${esc(m.location)}</div>`:''}${m.event?`<span class="tag">${esc(m.event)}</span>`:''}</div></article>`).join(''):'<div class="card emptyMemory">No memories yet. Be the first one in.</div>'}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function populate(){const opts=days.map(d=>`<option value="${d}">${fmtDay(d)}</option>`).join('');$('#memoryDay').innerHTML='<option value="all">All days</option>'+opts;$('#memoryDayForm').insertAdjacentHTML('beforeend',opts)}
function openFiles(files){pending=[...files];if(!pending.length)return;$('#preview').innerHTML=pending.map(f=>f.type.startsWith('image/')?`<img class="previewImg" src="${URL.createObjectURL(f)}">`:`<div class="card">🎥 ${esc(f.name)}</div>`).join('');$('#memoryDialog').showModal()}
async function submit(e){e.preventDefault();const author=$('#memoryAuthor').value.trim();if(!author||!pending.length)return;for(const f of pending){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});memories.unshift({id:'m-'+Date.now()+'-'+Math.random().toString(36).slice(2),kind:f.type.startsWith('image/')?'photo':f.type.startsWith('video/')?'video':'note',data,author,caption:$('#memoryCaption').value.trim(),day:$('#memoryDayForm').value,location:$('#memoryLocation').value.trim(),event:$('#memoryEvent').value.trim(),created_at:new Date().toISOString(),sync:'local'});await new Promise(r=>setTimeout(r,5))}save();pending=[];$('#memoryDialog').close();e.target.reset();render()}
$('#files').addEventListener('change',e=>openFiles(e.target.files));$('#cancelMemory').onclick=()=>$('#memoryDialog').close();$('#memoryForm').addEventListener('submit',submit);['memorySearch','memoryDay','memoryKind'].forEach(id=>$('#'+id).addEventListener('input',render));populate();render();
