const $=s=>document.querySelector(s);
const days=['2026-08-30','2026-08-31','2026-09-01','2026-09-02','2026-09-03','2026-09-04','2026-09-05'];
let pending=[];
let memories=JSON.parse(localStorage.getItem('playa_memory_depot')||'[]');
const API=window.PLAYA_API;
function fmtDay(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function save(){try{localStorage.setItem('playa_memory_depot',JSON.stringify(memories.filter(m=>m.sync==='local')))}catch(_){} }
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function contentUrl(m){return m.url||m.content_url||(API?`${API.base}/memories/${encodeURIComponent(m.id)}/content`:m.data||'')}
function render(){const q=$('#memorySearch').value.toLowerCase(),d=$('#memoryDay').value,k=$('#memoryKind').value;const arr=memories.filter(m=>(d==='all'||m.day===d)&&(k==='all'||m.kind===k)&&(!q||`${m.author} ${m.caption} ${m.location} ${m.event}`.toLowerCase().includes(q)));$('#memoryGrid').innerHTML=arr.length?arr.map(m=>`<article class="memoryCard card"><div class="memoryMedia">${m.kind==='photo'&&contentUrl(m)?`<img src="${esc(contentUrl(m))}" alt="${esc(m.caption||'Playa memory')}" loading="lazy">`:m.kind==='video'&&contentUrl(m)?`<video src="${esc(contentUrl(m))}" controls preload="metadata"></video>`:`<div class="memoryNote">✦<br><small>PLAYA NOTE</small></div>`}</div><div class="memoryInfo"><strong>${esc(m.caption||'Untitled memory')}</strong><div class="meta">${esc(m.author||'Anonymous')}${m.day?' · '+fmtDay(m.day):''}</div>${m.location?`<div class="meta">📍 ${esc(m.location)}</div>`:''}${m.event?`<span class="tag">${esc(m.event)}</span>`:''}${m.sync==='cloud'?`<span class="tag">☁ shared</span>`:`<span class="tag">local</span>`}</div></article>`).join(''):'<div class="card emptyMemory">No memories yet. Be the first one in.</div>'}
function populate(){const opts=days.map(d=>`<option value="${d}">${fmtDay(d)}</option>`).join('');$('#memoryDay').innerHTML='<option value="all">All days</option>'+opts;$('#memoryDayForm').insertAdjacentHTML('beforeend',opts)}
function openFiles(files){pending=[...files];if(!pending.length)return;$('#preview').innerHTML=pending.map(f=>f.type.startsWith('image/')?`<img class="previewImg" src="${URL.createObjectURL(f)}">`:`<div class="card">🎥 ${esc(f.name)}</div>`).join('');$('#memoryDialog').showModal()}
async function loadCloud(){if(!API)return;try{const r=await API.request('/memories',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(Array.isArray(data.memories)){memories=[...data.memories.map(m=>({...m,sync:'cloud'})),...memories.filter(m=>m.sync==='local')];render()}}catch(err){console.warn('Memory Depot cloud load unavailable',err)}}
async function uploadCloud(file,meta){const form=new FormData();form.append('file',file,file.name);Object.entries(meta).forEach(([k,v])=>form.append(k,v??''));const r=await API.request('/memories',{method:'POST',body:form,headers:{}});if(!r.ok)throw new Error(`Upload failed (${r.status})`);return r.json()}
async function submit(e){e.preventDefault();const author=$('#memoryAuthor').value.trim();if(!author||!pending.length)return;const meta={author,caption:$('#memoryCaption').value.trim(),day:$('#memoryDayForm').value,location:$('#memoryLocation').value.trim(),event:$('#memoryEvent').value.trim()};const button=e.target.querySelector('button.primary');button.disabled=true;button.textContent='Uploading…';try{for(const f of pending){if(f.size>25*1024*1024)throw new Error(`${f.name} is over the 25 MB upload limit for the current depot setup.`);if(API){const cloud=await uploadCloud(f,meta);memories.unshift({...cloud,sync:'cloud'})}else{throw new Error('Cloud API is not configured.')};}pending=[];$('#memoryDialog').close();e.target.reset();render()}catch(err){alert(`Memory Depot could not upload this item yet.\n\n${err.message}\n\nYour files were not discarded.`)}finally{button.disabled=false;button.textContent='Add to depot'}}
$('#files').addEventListener('change',e=>openFiles(e.target.files));$('#cancelMemory').onclick=()=>{$('#memoryDialog').close();pending=[]};$('#memoryForm').addEventListener('submit',submit);['memorySearch','memoryDay','memoryKind'].forEach(id=>$('#'+id).addEventListener('input',render));populate();render();loadCloud();
